# Generated by Django 5.2.8 on 2025-11-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer_newsletter_abo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='newsletter_abo',
            field=models.BooleanField(default=False),
        ),
    ]
